[package]
name = "repetitive"
categories = ["rust-patterns"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Noam2Stein/repetitive"
rust-version = "1.97"
description = "A metaprogramming macro with control flow syntax"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.107"

[dev-dependencies]
indoc = "2.0.7"
itertools = "0.15.0"
prettyplease = "0.3.0"
quote = "1.0.47"
syn = "3.0.3"
