[package]
edition = "2024"
name    = "repetitive"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2     = "1.0.95"
quote           = "1.0.40"
string-interner = "0.19.0"
syn             = { version = "2.0.104", features = [ "full" ] }
