name: Verify

on:
  push:
    branches:
      - main

  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.97.0"
          target: x86_64-unknown-linux-gnu
          components: rustfmt
      - uses: Swatinem/rust-cache@master

      - name: Fmt Check
        run: cargo fmt --check --all

  doc:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.97.0"
          target: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@master

      - name: Doc
        run: cargo doc --no-deps

  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.97.0"
          target: x86_64-unknown-linux-gnu
          components: clippy
      - uses: Swatinem/rust-cache@master

      - name: Clippy
        run: cargo clippy --all-targets

  test:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.97.0"
          target: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@master

      - name: Test
        run: cargo test
