name: Verify

on:
  push:
    branches:
      - main

  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  Everything:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: "1.97.0"
        target: x86_64-unknown-linux-gnu
        components: clippy
    - uses: Swatinem/rust-cache@master

    - name: Fmt Check
      run: cargo fmt --check --all

    - name: Doc
      run: cargo doc --no-deps

    - name: Clippy
      run: cargo clippy --all-targets

    - name: Test
      run: cargo test

